config/routes.rb
Rails.application.routes.draw do


  root 'dashboard#index', as: :dashboards
  resources :posts
  resource :registration, only: [:new, :create]
  resource :logins, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def current_user
    @user = User.find_by(id: session[:user_id])
  end

  def valid_user_presence
    @user = User.find_by(id: session[:user_id])
    redirect_to new_logins_path unless @user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    user = User.find_by(id: session[:user_id])
    redirect_to new_logins_path unless user
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)

    if @user
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "Email or password is wrong!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session.delete(:current_user_id)

    @_current_user = nil
    redirect_to root
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :valid_user_presence, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @user = User.find_by(id: session[:user_id])
    @posts = Post.all
  end
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      flash[:alert] = "Couldn't create the Post!"
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to post_path, status: :see_other
  end

  def correct_user
    @post = Post.find(params[:id])
    @user = User.find_by(id: session[:user_id])
    if @user.id != @post.user_id
      redirect_to posts_path
      flash[:notice] = "You are not authorized to edit that post"
    end
  end
  private

  def set_post
    @post = Post.find(params[:id])

  end

  def post_params
    params.require(:post).permit(:title,:body,:user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_logins_path
    else
      flash[:alert] = "Couldn't save the User!"
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    session.delete(:current_user_id)

    @_current_user = nil
    redirect_to root
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div><%= notice %></div>
  <div><%= alert %></div>
  <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Log in</h1>

<%= form_with model: @user, url: logins_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Log In" %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <div>
    <%= form.label :user_id %>
    <%= form.number_field  :user_id, id: :post_user_id, value: @user.id %>
  </div>
  <%= form.submit "Submit" %>
<% end %>

app/views/posts/edit.html.erb
<%= render "posts/form", post: @post %>

app/views/posts/index.html.erb
<div style="padding: 4em">

<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>
  <%= link_to "New  Post", new_post_path %>
<table>
  <thead >
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>POST ID</th>
    <th>User ID</th>
    <th colspan="2">Actions</th>

  </tr>
  </thead>
  <tbody>

    <% @posts.each do |post| %>
    <tr>
      <td> Title:  <%= link_to post.title, post %>  </td>
      <td> Body:  <%= post.body %>  </td>
      <td> ID:  <%= post.id %>  </td>
      <td> User ID: <%= post.user_id %>  </td>
      <% if post.user_id == @user.id %>
      <td>  <%= link_to "Edit", edit_post_path(post.id) %>  </td>
      <td>  <%= link_to "Destroy", post_path(post), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>  </td>
        <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/posts/new.html.erb
<h1>Post new</h1>
<%= render "posts/form" %>

app/views/posts/show.html.erb
<h1>Post#show</h1>
<p>Find me in app/views/post/show.html.erb</p>
<p><%= @post.title %></p>
<p><%= @post.body %></p>
<p><%= @post.user_id %></p>

app/views/posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>

app/views/shared/_header.html.erb
<ul>
  <li><%= link_to 'home', dashboards_path  %></li>
  <li><%= link_to "Posts", posts_path %></li>
  <li><%= link_to "Sign Up", new_registration_path %></li>
  <li><%= link_to "Log In", new_logins_path %></li>
</ul>